// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Relais.Infrastructure.Persistence;

#nullable disable

namespace Relais.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RelaisDbContext))]
    [Migration("20260909105759_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Relais.Domain.Entities.Beneficiaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReferentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReferentId");

                    b.ToTable("Beneficiaires");
                });

            modelBuilder.Entity("Relais.Domain.Entities.JournalAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cible")
                        .HasColumnType("text");

                    b.Property<DateTime>("Horodatage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("JournalAudit");
                });

            modelBuilder.Entity("Relais.Domain.Entities.ParametresInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DureeConservationJours")
                        .HasColumnType("integer");

                    b.Property<string>("EmailContact")
                        .HasColumnType("text");

                    b.Property<string>("NomInstitution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ParametresInstallation");
                });

            modelBuilder.Entity("Relais.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EstAlerte")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0105df6-66ee-4503-9c4e-77aee63f9395"),
                            EstAlerte = false,
                            Libelle = "Comportement"
                        },
                        new
                        {
                            Id = new Guid("ad95982c-900a-416e-bce4-e24b9a729fba"),
                            EstAlerte = false,
                            Libelle = "Santé"
                        },
                        new
                        {
                            Id = new Guid("d07a332c-5537-48ea-9b8a-9087973cbdf2"),
                            EstAlerte = false,
                            Libelle = "Repas / sommeil"
                        },
                        new
                        {
                            Id = new Guid("4ddf7bc6-35de-4f5f-90f0-409a4a6805c2"),
                            EstAlerte = false,
                            Libelle = "Activité"
                        },
                        new
                        {
                            Id = new Guid("3f938b76-df33-4ee6-af67-9725234982f3"),
                            EstAlerte = false,
                            Libelle = "Point positif"
                        },
                        new
                        {
                            Id = new Guid("612c7506-2a74-40f2-853f-f1acb487968c"),
                            EstAlerte = true,
                            Libelle = "À signaler"
                        });
                });

            modelBuilder.Entity("Relais.Domain.Entities.Transmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuteurId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BeneficiaireId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifieLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.HasIndex("BeneficiaireId");

                    b.ToTable("Transmissions");
                });

            modelBuilder.Entity("Relais.Domain.Entities.TransmissionTag", b =>
                {
                    b.Property<Guid>("TransmissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("TransmissionId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TransmissionTag");
                });

            modelBuilder.Entity("Relais.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Relais.Domain.Entities.Beneficiaire", b =>
                {
                    b.HasOne("Relais.Domain.Entities.Utilisateur", "Referent")
                        .WithMany()
                        .HasForeignKey("ReferentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Referent");
                });

            modelBuilder.Entity("Relais.Domain.Entities.JournalAudit", b =>
                {
                    b.HasOne("Relais.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Relais.Domain.Entities.Transmission", b =>
                {
                    b.HasOne("Relais.Domain.Entities.Utilisateur", "Auteur")
                        .WithMany()
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Relais.Domain.Entities.Beneficiaire", "Beneficiaire")
                        .WithMany("Transmissions")
                        .HasForeignKey("BeneficiaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Beneficiaire");
                });

            modelBuilder.Entity("Relais.Domain.Entities.TransmissionTag", b =>
                {
                    b.HasOne("Relais.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relais.Domain.Entities.Transmission", "Transmission")
                        .WithMany("TransmissionTags")
                        .HasForeignKey("TransmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Transmission");
                });

            modelBuilder.Entity("Relais.Domain.Entities.Beneficiaire", b =>
                {
                    b.Navigation("Transmissions");
                });

            modelBuilder.Entity("Relais.Domain.Entities.Transmission", b =>
                {
                    b.Navigation("TransmissionTags");
                });
#pragma warning restore 612, 618
        }
    }
}
